# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    upload_to_play_store(
      track: "internal",
      rollout: "1",
      aab: "../build/app/outputs/bundle/release/tudo_android.aab",
      mapping: "../build/app/outputs/mapping/release/mapping.txt"
    )
  end
end
