name: Linux x86-64
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load config
        run: echo "${{ secrets.CONFIG }}" > lib/config.dart

      - uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Install dev tools
        run: sudo apt-get install ninja-build build-essential libgtk-3-0 libgtk-3-dev libblkid1 liblzma5

      - name: Build app
        run: flutter build linux

      - name: Create archive
        working-directory: build/linux/x64/release/bundle
        run: tar -acf tudo_linux_x86_64.tar.gz *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux_x86_64
          path: build/linux/x64/release/bundle/tudo_linux_x86_64.tar.gz